Logger
it-top-vrn/Messenger pull request #2
Opened 2021-06-14 17:23 UTC by iliynsd

Функции журналирования событий(в файл)

2021-06-14 17:28 UTC, iliynsd commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создание модуля журналирования](https://trello.com/c/TrVYc7mw/5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F-%D0%B6%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

2021-06-14 17:34 UTC, anst-foto requested changes
- Переименовать названия файлов в соответствии с содержимым.
- Предусмотреть возможность логирования в локальную БД (SQLite) _(на усмотрение команды)_
- Предусмотреть методы для основных операций логирования, без выбора типа операции _(на усмотрение команды)_

2021-06-14 17:34 UTC, anst-foto commented on DB_API/Class1.cs
>      public class Class1
Пустой класс

2021-06-14 18:04 UTC, Kizeldur requested changes
Доработать, см. комменты

2021-06-14 18:04 UTC, Kizeldur commented on Logger/Class1.cs
> +            await WriteToFile($"{DateTime.Now:u} [{type}] {message}");
Определение времени в этой и следующей функциях нежелательно. Было уже до этого решено, что время и прочие данные будут определяться на сервере, а затем отсылаться в журнал и БД при помощи соответствующих методов. Можно, конечно и так, но это может привести к разным формам записи данных в БД и журнале

2021-06-14 18:04 UTC, Kizeldur commented on Logger/Class1.cs
> +            }
Асинхронность здесь не нужна, она будет реализована на сервере.

2021-06-14 18:04 UTC, Kizeldur commented on Logger/Class1.cs
> +            }
Также желательно подключение к файлу и проверку на подключение в отдельную функцию или в конструктор. Функция WriteToFile по определению должна только записывать в файл. Все проверки должны выполняться другой функцией. всю эту часть можно просто перенести в конструктор, логично, что при вызове конструктора LogToFile он будет подключаться к файлу. Для этого нужно еще создать переменную-поле, где будет храниться файл. Также нужна функция для закрытия файла

2021-06-14 18:04 UTC, Kizeldur commented on Logger/Class1.cs
> +            await WriteToFile($"{DateTime.Now:u} [{type}] {message}");
Эти функции нужно будет доработать, когда будет решено, какие данные и в каком виде будут присылаться

2021-06-14 18:24 UTC, anst-foto commented on Logger/Class1.cs
> +            await WriteToFile($"{DateTime.Now:u} [{type}] {message}");
https://github.com/itstep-vrn/Messenger/pull/2#discussion_r651152818
Здесь нужно время - это система логирования/журналирования событий как на клиенте так и на сервере. Событий программы. А не запись сообщений пользователей в БД

2021-06-14 18:25 UTC, anst-foto commented on Logger/Class1.cs
> +            }
> Асинхронность здесь не нужна, она будет реализована на сервере.

Не соглашусь. Это отдельный модуль. Он с сервером не связан. Это сервер его использует.

2021-06-14 18:27 UTC, anst-foto commented on Logger/Class1.cs
> +            }
> Также желательно подключение к файлу и проверку на подключение в отдельную функцию или в конструктор. Функция WriteToFile по определению должна только записывать в файл. Все проверки должны выполняться другой функцией. всю эту часть можно просто перенести в конструктор, логично, что при вызове конструктора LogToFile он будет подключаться к файлу. Для этого нужно еще создать переменную-поле, где будет храниться файл. Также нужна функция для закрытия файла

Отдельный метод на закрытие не нужен, т.к. используется `using` он сам инициализирует закрытие доступа к файлу

2021-06-14 18:28 UTC, anst-foto commented on Logger/Class1.cs
> +            }
Отдельную функцию на проверку на подключение - можно и не делать. Но вот добавить события на ошибки - можно.

2021-06-17 17:18 UTC, anst-foto requested changes
Разнести классы по разным файлам

2021-06-17 17:54 UTC, anst-foto requested changes
Сделать единообразные методы во всех классах. Придумать Интерфейс для них.
Не скупиться на имена переменных!

2021-06-23 16:14 UTC, anst-foto reviewed
Посмотри пожелание по проверке пути к файлу

2021-06-23 16:14 UTC, anst-foto commented on Logger/LogToFile.cs
> +{ public delegate void Message(string message);
```suggestion
{ 
    public delegate void Message(string message);
```

2021-06-23 16:14 UTC, anst-foto commented on Logger/LogToFile.cs
> +        }
Сделать проверку на правильность указания пути к файлу

2021-06-23 16:14 UTC, anst-foto commented on Logger/LogType.cs
> +}
```suggestion
}

```

2021-07-07 12:46 UTC, merged